apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloud-torrent.fullname" . }}
  labels:
    {{- include "cloud-torrent.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cloud-torrent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cloud-torrent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cloud-torrent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.pvc.enabled }}
      volumes:
      - name: {{ include "cloud-torrent.fullname" . }}-downloads
        persistentVolumeClaim:
          claimName: {{ include "cloud-torrent.fullname" . }}-downloads
      - name: {{ include "cloud-torrent.fullname" . }}-torrents
        persistentVolumeClaim:
          claimName: {{ include "cloud-torrent.fullname" . }}-torrents
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.pvc.enabled }}
          volumeMounts:
            - mountPath: {{ .Values.pvc.downloads.mountPath }}
              name: {{ include "cloud-torrent.fullname" . }}-downloads
            - mountPath: {{ .Values.pvc.torrents.mountPath }}
              name: {{ include "cloud-torrent.fullname" . }}-torrents
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
