apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cloud-torrent.fullname" . }}-downloads
  labels:
    {{- include "cloud-torrent.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.downloads.storage }}
